### PR TITLE
implementation of sort command closes #112, closes #111, closes #110

### LINKED ISSUE #110: Sort address book lexicographically by users' names

### LINKED ISSUE #111: As an insurance agent, I want to be able to sort my address book by name so I stay organized

### LINKED ISSUE #112: Implement custom Comparator class to allow comparing Person objects
Necessary for sorting

### PR DESCRIPTION
**Pull request by luca590**
TODO: test cases and UD

### CODE REVIEW

**Comment by jlks96** [comment]
Please put your references to issues as comments and not in the title (not detected by the issues).

**Comment by luca590** [comment]
satisfies #110 
satisfies #112  
satisfies #113  
satisfies #114

**Comment by jlks96** [comment]
There were some conflicts in the UG. I resolved the conflicts for you already.

**Review by jlks96 — COMMENTED** [review]
1) command word should be "sort", command alias "so" (for consistency)
2) Maybe rename PersonCompare to PersonComparator?
3) Try not to include commented out code (SortCommandTest)
4) You want to make sorting undoable?

**Review by jlks96 — COMMENTED** [review]
Please do not remove gradlew batch file next time. Else wont run gradlew command

**Pull request merged**
