### PR TITLE
Merging master after resolving conflicts with ImportExcel

### PR DESCRIPTION
**Pull request by luca590**

### CODE REVIEW

**Comment by luca590** [comment]
Strange build failure... not sure what's wrong

**Comment by jlks96** [comment]
possible to PR from a branch without other irrelevant commits?

**Comment by jlks96** [comment]
Stash the changes and move it to a new branch, for eg

**Review by jlks96 — CHANGES_REQUESTED** [review]
1) PR from a clean branch without all irrelevant commits
2) Why the changes in build scripts?

**Comment by ng95junwei** [comment]
perhaps you could branch this off, revert this to the point you forked, pull from master and use cherry pick to pick your commits from this branch. I think that will clean up the PR alot!

**Pull request closed without merging**
