### PR TITLE
Refactor across project to use NameContainsFullKeywordPredicate

### PR DESCRIPTION
**Pull request by ng95junwei**

### CODE REVIEW

**Comment by jlks96** [comment]
CI failed. Try looking out for format error due to whitespaces.

**Comment by tshradheya** [comment]
Note: Make PR from your fork and not from the team repo :P

**Comment by ng95junwei** [comment]
Will remake the PR on my own fork

**Comment by tshradheya** [comment]
I think you misunderstood my point.
Make PR on this repo itself but the branch you need to make PR from needs to be from your fork.
So basically, clone your fork and branch from that instead of branching out from the team repo :P

**Pull request closed without merging**
