### PR TITLE
additional explination for ec without file path and improved import contacts error closes #137, closes #134, closes #127

### LINKED ISSUE #127: Import and Export contacts is misleading
**Not too sure how detailed the file path needs to be:**
ic mydata.csv doesn't work but ic data/mydata.csv works.
In UG example `import_contacts f/examplefile.csv` and `ec data/newFileExample.csv` should have the same path cause it's misleading that one is created in data file path, one is created in current file path

In UG it says f/PATH but f/ is not a prefix for both ec and ic

<sub>[original: nus-cs2103-AY1718S2/pe-round1#331]</sub>

 Issue created by: @sherlynng

### LINKED ISSUE #134: error message on `import_contacts` not user friendly
# To reproduce:

`import_contacts .csv`
image

<sub>[original: nus-cs2103-AY1718S2/pe-round1#654]</sub>

 Issue created by: @jethrokuan

### LINKED ISSUE #137: `export_contacts` without parameters specified passes
# To Reproduce:

`export_contacts`
image

## Expected result:
error, request to specify path to export to

<sub>[original: nus-cs2103-AY1718S2/pe-round1#723]</sub>

 Issue created by: @jethrokuan

### PR DESCRIPTION
**Pull request by luca590**
resolves #137

### CODE REVIEW

**Comment by luca590** [comment]
resolves #134

**Comment by luca590** [comment]
resolves #127

**Review by jlks96 — COMMENTED** [review]
Possible to create a command stub for testing instead of specifying in UG?

**Comment by jlks96** [comment]
I will just merge this for v1.5rc. Please KIV the comment above.

**Pull request merged**
