### PR TITLE
Import csv class

### PR DESCRIPTION
**Pull request by luca590**

### CODE REVIEW

**Comment by luca590** [comment]
oh my god

**Review by jlks96 — COMMENTED** [review]
For consistency purpose, could you change the format of import contacts to "importcontacts [f/PATH]" and give examples of usage, eg importcontacts f/User/username/examplefile.csv (followed by explanation)
To be done: create a parser for the import command and add it to the address book parser & add tests

**Review by jlks96 — COMMENTED** [review]
yes to adding f/

**Comment by luca590** [comment]
Is this merge okay? There are still checkstyle errors, would prefer to fix those later

**Comment by jlks96** [comment]
Just fix those first to make sure CI works. Unmerge and merge again once fixed before moving on.

**Pull request merged**
