### PR TITLE
Added delete dated contacts function

### PR DESCRIPTION
**Pull request by jlks96**
-new tests are yet to be added and some existing tests are yet to be resolved

### CODE REVIEW

**Comment by ng95junwei** [comment]
This is an extremely large PR. Perhaps next time it would be better to split the updates into different iterations and hence different PRs so that the PR is cleaner.

**Comment by ng95junwei** [comment]
I noticed you deleted the tempAddressbook.xml. Any reason for that/ any dependencies on that?

**Comment by jlks96** [comment]
tempAddressbook.xml is not used for any of the tests hence the removal

**Comment by jlks96** [comment]
related to #49 #68

**Pull request merged**
